import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

// ESM compatibility for __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Screenshot generation for FHIR Scheduler Widget documentation
 * 
 * This test suite:
 * 1. Captures screenshots at each step of the booking flow
 * 2. Generates SCREENSHOTS.md with the screenshot documentation
 * 
 * Run with: npx playwright test tests/screenshots.spec.ts
 * Screenshots saved to: docs/screenshots/
 * Documentation saved to: docs/SCREENSHOTS.md
 */

// Single source of truth for all screenshots
const SCREENSHOTS = [
  {
    id: '00-visit-type',
    title: 'Visit Type Selection',
    description: 'Choose between follow-up or new patient visit',
    category: 'flow',
  },
  {
    id: '00b-questionnaire',
    title: 'New Patient Intake Questionnaire',
    description: 'Questionnaire for new patients before scheduling',
    category: 'flow',
  },
  {
    id: '01-provider-list',
    title: 'Provider Selection',
    description: 'Browse and select from available providers',
    category: 'flow',
  },
  {
    id: '02-date-selection',
    title: 'Date Selection with Availability',
    description: 'View available dates with slot counts',
    category: 'flow',
  },
  {
    id: '03-calendar-view',
    title: 'Calendar View',
    description: 'Alternative calendar-based date picker',
    category: 'flow',
  },
  {
    id: '04-time-slots',
    title: 'Time Slot Selection',
    description: 'Choose from available appointment times',
    category: 'flow',
  },
  {
    id: '05-booking-form',
    title: 'Booking Form with Hold Timer',
    description: 'Complete booking with slot reservation countdown',
    category: 'flow',
  },
  {
    id: '06-booking-filled',
    title: 'Completed Form',
    description: 'Booking form with patient information entered',
    category: 'flow',
  },
  {
    id: '07-confirmation',
    title: 'Confirmation',
    description: 'Appointment successfully booked',
    category: 'flow',
  },
  {
    id: '08-mobile-provider-list',
    title: 'Mobile Provider List',
    description: 'Responsive mobile view of provider selection',
    category: 'mobile',
  },
  {
    id: '09-mobile-booking',
    title: 'Mobile Booking Form',
    description: 'Responsive mobile view of booking form',
    category: 'mobile',
  },
];

/**
 * Generate markdown documentation from screenshot metadata
 */
function generateMarkdown(): string {
  const flowScreenshots = SCREENSHOTS.filter(s => s.category === 'flow');
  const mobileScreenshots = SCREENSHOTS.filter(s => s.category === 'mobile');

  let md = `# FHIR Scheduler Screenshots

This documentation is auto-generated by the screenshot tests.
Run \`npx playwright test tests/screenshots.spec.ts\` to regenerate.

## Booking Flow

`;

  for (const screenshot of flowScreenshots) {
    md += `### ${screenshot.title}\n`;
    md += `${screenshot.description}\n\n`;
    md += `![${screenshot.title}](screenshots/${screenshot.id}.png)\n\n`;
  }

  md += `## Mobile Responsive

| ${mobileScreenshots.map(s => s.title).join(' | ')} |
|${mobileScreenshots.map(() => '---').join('|')}|
| ${mobileScreenshots.map(s => `![${s.title}](screenshots/${s.id}.png)`).join(' | ')} |
`;

  return md;
}

/**
 * Generate the README screenshots section
 */
function generateReadmeSection(): string {
  const flowScreenshots = SCREENSHOTS.filter(s => s.category === 'flow');
  const mobileScreenshots = SCREENSHOTS.filter(s => s.category === 'mobile');

  let md = `## Screenshots

`;

  for (const screenshot of flowScreenshots) {
    md += `### ${screenshot.title}\n`;
    md += `![${screenshot.title}](docs/screenshots/${screenshot.id}.png)\n\n`;
  }

  md += `### Mobile Responsive
| ${mobileScreenshots.map(s => s.title.replace('Mobile ', '')).join(' | ')} |
|${mobileScreenshots.map(() => '------------').join('|')}|
| ${mobileScreenshots.map(s => `![${s.title}](docs/screenshots/${s.id}.png)`).join(' | ')} |
`;

  return md;
}

test.describe('Documentation Screenshots', () => {
  /**
   * Helper to select follow-up visit type (skips questionnaire)
   */
  async function selectFollowUpVisit(page: import('@playwright/test').Page) {
    await expect(page.getByRole('button', { name: /follow-up visit/i })).toBeVisible({ timeout: 10000 });
    await page.getByRole('button', { name: /follow-up visit/i }).click();
  }

  /**
   * Helper to navigate to booking form step (follow-up flow)
   */
  async function navigateToBookingForm(
    page: import('@playwright/test').Page,
    dateIndex = 0,
    slotIndex = 0
  ) {
    await selectFollowUpVisit(page);
    await expect(page.getByRole('button', { name: /Select Dr\./ }).first()).toBeVisible({ timeout: 10000 });
    await page.getByRole('button', { name: /Select Dr\./ }).first().click();
    await expect(page.getByRole('option').first()).toBeVisible({ timeout: 10000 });
    await page.getByRole('option').nth(dateIndex).click();
    await expect(page.getByRole('option', { name: /AM|PM/ }).first()).toBeVisible({ timeout: 10000 });
    // Use last() when slotIndex is -1 to avoid slot conflicts
    const slotLocator = page.getByRole('option', { name: /AM|PM/ });
    if (slotIndex === -1) {
      await slotLocator.last().click();
    } else {
      await slotLocator.nth(slotIndex).click();
    }
    await expect(page.getByRole('heading', { name: 'Complete Your Booking' })).toBeVisible({ timeout: 10000 });
  }

  /**
   * Take a screenshot with consistent settings
   */
  async function takeScreenshot(page: import('@playwright/test').Page, id: string, fullPage = false) {
    await page.waitForTimeout(500);
    await page.screenshot({
      path: `docs/screenshots/${id}.png`,
      fullPage,
    });
  }

  // Generate documentation at the end of all tests
  test.afterAll(async () => {
    const docsDir = path.join(__dirname, '..', 'docs');
    
    // Write SCREENSHOTS.md
    const markdown = generateMarkdown();
    fs.writeFileSync(path.join(docsDir, 'SCREENSHOTS.md'), markdown);
    
    // Write README section to a separate file for reference
    const readmeSection = generateReadmeSection();
    fs.writeFileSync(path.join(docsDir, 'README-SCREENSHOTS.md'), readmeSection);
    
    console.log('\n📸 Generated docs/SCREENSHOTS.md');
    console.log('📝 Generated docs/README-SCREENSHOTS.md (copy to README.md Screenshots section)');
  });

  test('00-visit-type: Visit type selection', async ({ page }) => {
    await page.setViewportSize({ width: 1024, height: 768 });
    await page.goto('http://localhost:5174/');
    await expect(page.getByRole('heading', { name: 'Schedule an Appointment' })).toBeVisible({ timeout: 10000 });
    await takeScreenshot(page, '00-visit-type');
  });

  test('00b-questionnaire: New patient questionnaire', async ({ page }) => {
    await page.setViewportSize({ width: 1024, height: 768 });
    await page.goto('http://localhost:5174/');
    await page.getByRole('button', { name: /new patient visit/i }).click();
    await expect(page.getByRole('heading', { name: 'Patient Intake' })).toBeVisible({ timeout: 10000 });
    await takeScreenshot(page, '00b-questionnaire');
  });

  test('01-provider-list: Provider selection', async ({ page }) => {
    await page.setViewportSize({ width: 1024, height: 768 });
    await page.goto('http://localhost:5174/');
    await selectFollowUpVisit(page);
    await expect(page.getByRole('heading', { name: 'Select a Provider' })).toBeVisible({ timeout: 10000 });
    await takeScreenshot(page, '01-provider-list');
  });

  test('02-date-selection: Available dates', async ({ page }) => {
    await page.setViewportSize({ width: 1024, height: 768 });
    await page.goto('http://localhost:5174/');
    await selectFollowUpVisit(page);
    await page.getByRole('button', { name: /Select Dr\./ }).first().click();
    await expect(page.getByRole('tab', { name: 'Available' })).toBeVisible({ timeout: 10000 });
    await takeScreenshot(page, '02-date-selection');
  });

  test('03-calendar-view: Calendar tab', async ({ page }) => {
    await page.setViewportSize({ width: 1024, height: 768 });
    await page.goto('http://localhost:5174/');
    await selectFollowUpVisit(page);
    await page.getByRole('button', { name: /Select Dr\./ }).first().click();
    await page.getByRole('tab', { name: 'Calendar' }).click();
    await takeScreenshot(page, '03-calendar-view');
  });

  test('04-time-slots: Time slot selection', async ({ page }) => {
    await page.setViewportSize({ width: 1024, height: 768 });
    await page.goto('http://localhost:5174/');
    await selectFollowUpVisit(page);
    await page.getByRole('button', { name: /Select Dr\./ }).first().click();
    await page.getByRole('option').first().click();
    await expect(page.getByRole('region', { name: 'Available times' })).toBeVisible({ timeout: 10000 });
    await takeScreenshot(page, '04-time-slots');
  });

  test('05-booking-form: Booking form with hold timer', async ({ page }) => {
    await page.setViewportSize({ width: 1024, height: 768 });
    await page.goto('http://localhost:5174/');
    await navigateToBookingForm(page, 15, -1);
    await expect(page.getByText(/Slot reserved for/)).toBeVisible();
    await takeScreenshot(page, '05-booking-form');
  });

  test('06-booking-filled: Completed form', async ({ page }) => {
    await page.setViewportSize({ width: 1024, height: 768 });
    await page.goto('http://localhost:5174/');
    await navigateToBookingForm(page, 17, -1);
    await page.locator('#fs-name').fill('Jane Smith');
    await page.locator('#fs-email').fill('jane.smith@example.com');
    await page.locator('#fs-phone').fill('(555) 123-4567');
    await page.locator('#fs-reason').fill('Annual checkup');
    await takeScreenshot(page, '06-booking-filled');
  });

  test('07-confirmation: Booking confirmation', async ({ page }) => {
    await page.setViewportSize({ width: 1024, height: 768 });
    await page.goto('http://localhost:5174/');
    await navigateToBookingForm(page, 19, -1);
    await page.locator('#fs-name').fill('Test Patient');
    await page.locator('#fs-email').fill('test@example.com');
    await page.locator('#fs-phone').fill('(555) 000-0000');
    await page.getByRole('button', { name: 'Confirm Booking' }).click();
    await expect(page.getByRole('heading', { name: 'Appointment Confirmed!' })).toBeVisible({ timeout: 15000 });
    await takeScreenshot(page, '07-confirmation');
  });

  test('08-mobile-provider-list: Mobile provider list', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await page.goto('http://localhost:5174/');
    await selectFollowUpVisit(page);
    await expect(page.getByRole('heading', { name: 'Select a Provider' })).toBeVisible({ timeout: 10000 });
    await takeScreenshot(page, '08-mobile-provider-list');
  });

  test('09-mobile-booking: Mobile booking form', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 667 });
    await page.goto('http://localhost:5174/');
    await selectFollowUpVisit(page);
    await page.getByRole('button', { name: /Select Dr\./ }).first().click();
    await page.getByRole('option').nth(21).click();
    await page.getByRole('option', { name: /AM|PM/ }).last().click();
    await expect(page.getByRole('heading', { name: 'Complete Your Booking' })).toBeVisible({ timeout: 10000 });
    await takeScreenshot(page, '09-mobile-booking', true);
  });
});
