events {
    worker_connections 1024;
}

http {
    upstream inferno {
        server inferno:4567;
    }

    upstream validator {
        server hl7_validator_service:4567;
    }

    server {
        listen 80;

        # Inferno API and UI
        location / {
            proxy_pass http://inferno;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # HL7 Validator
        location /hl7validatorapi/ {
            proxy_pass http://validator/;
            proxy_set_header Host $host;
        }
    }
}
